/**
 * Generate research/INDEX.md — living knowledge base map.
 *
 * Usage: npx tsx automation/scripts/kb-index.ts
 */
import { readdirSync, statSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';

const root = join(__dirname, '../..');
const researchRoot = join(root, 'research');

function walk(dir: string, acc: string[] = []): string[] {
  if (!existsSync(dir)) return acc;
  for (const name of readdirSync(dir)) {
    if (name === 'INDEX.md' || name === 'LATEST-DIGEST.md') continue;
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walk(p, acc);
    else if (name.endsWith('.md') || name.endsWith('.mdx')) acc.push(p);
  }
  return acc;
}

function firstHeading(path: string): string {
  const text = readFileSync(path, 'utf8');
  const m = text.match(/^#\s+(.+)$/m);
  return m?.[1]?.trim() || relative(researchRoot, path);
}

const files = walk(researchRoot).sort();
const byDir: Record<string, string[]> = {};
for (const f of files) {
  const rel = relative(researchRoot, f);
  const dir = rel.includes('/') ? rel.split('/')[0] : '.';
  (byDir[dir] ||= []).push(f);
}

const dataFiles = [
  'timeline.json',
  'specs.json',
  'heritage.json',
  'tasks.json',
  'telemetry.json',
  'funding.json',
  'mass-budget.json',
  'risks.json',
  'partners.json',
  'mission-control.json',
].map((f) => `site/content/data/${f}`);

const md = `# Research & mission knowledge base

_Auto-generated by \`automation/scripts/kb-index.ts\` · ${new Date().toISOString()}_  
**Do not hand-edit** — re-run the script after adding notes.

## How to use

| Audience | Start here |
|----------|------------|
| Agents | \`AGENTS.md\` (repo root) + this index |
| Science | \`research/science/\` |
| Competitors | \`research/competitors/\` |
| Weekly ops | \`research/notes/LATEST-DIGEST.md\` |
| Site truth | \`site/content/data/*.json\` |

## Structured mission data (source of truth)

${dataFiles.map((f) => `- [\`${f}\`](../${f})`).join('\n')}

## Knowledge base files

${Object.keys(byDir)
  .sort()
  .map((dir) => {
    const list = byDir[dir]
      .map((f) => {
        const rel = relative(researchRoot, f);
        return `  - [${firstHeading(f)}](./${rel}) — \`${rel}\``;
      })
      .join('\n');
    return `### ${dir}/\n\n${list}`;
  })
  .join('\n\n')}

## Update cadence

| Cadence | Action |
|---------|--------|
| Weekly (Mon) | Research scaffold PR + mission digest |
| On content change | Metrics one-pager + social drafts |
| On demand | \`npx tsx automation/scripts/evolve.ts kb\` |
| Human review | Never auto-merge research findings |

## Open questions

See [open-questions.md](./notes/open-questions.md) — resolve into science/competitors notes, then check off.
`;

writeFileSync(join(researchRoot, 'INDEX.md'), md, 'utf8');
console.log('Wrote research/INDEX.md');
console.log(`Indexed ${files.length} markdown files.`);
