/**
 * Weekly mission digest from structured data + research KB.
 * Output: research/notes/YYYY-MM-DD-mission-digest.md
 *
 * Usage: npx tsx automation/scripts/mission-digest.ts
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const root = join(__dirname, '../..');
const date = process.env.DIGEST_DATE || new Date().toISOString().slice(0, 10);

function load<T>(rel: string): T {
  return JSON.parse(readFileSync(join(root, rel), 'utf8')) as T;
}

type Task = { id: string; title: string; status: string; priority: string; area: string };
type Risk = { id: string; title: string; likelihood: string; impact: string; status: string };
type Partner = { id: string; name: string; status: string; priority: string; next_step: string };
type Check = { id: string; item: string; status: string; due?: string };
type Telemetry = { overall_status: string; mission_phase: string; systems: { label: string; status: string }[] };

const tasks = load<Task[]>('site/content/data/tasks.json');
const risks = load<{ risks: Risk[] }>('site/content/data/risks.json').risks;
const partners = load<{ pipeline: Partner[] }>('site/content/data/partners.json').pipeline;
const mc = load<{ phase: string; callsign: string; checklist: Check[]; funding_goal_usd: number }>(
  'site/content/data/mission-control.json'
);
const telemetry = load<Telemetry>('site/content/data/telemetry.json');
const funding = load<{ tiers: Record<string, { capacity: number; baseline_allocated: number; name: string }> }>(
  'site/content/data/funding.json'
);
const mass = load<{ wet_mass_kg: number; target_float_altitude_km: number }>(
  'site/content/data/mass-budget.json'
);
const timeline = load<{ year: string; event: string; status: string }[]>(
  'site/content/data/timeline.json'
);

const openTasks = tasks.filter((t) => t.status === 'planned' || t.status === 'in_progress');
const p0 = openTasks.filter((t) => t.priority === 'P0');
const openRisks = risks.filter((r) => r.status === 'open' || r.status === 'mitigating');
const criticalRisks = openRisks.filter((r) => r.impact === 'critical' || r.impact === 'high');
const partnerActions = partners.filter((p) => p.status !== 'closed' && p.status !== 'won');
const checksOpen = mc.checklist.filter((c) => c.status !== 'done' && c.status !== 'cancelled');

const researchNotes = existsSync(join(root, 'research/notes'))
  ? readdirSync(join(root, 'research/notes')).filter((f) => f.endsWith('.md')).slice(-5)
  : [];

const md = `# Mission digest — ${date}

> Auto-generated by \`automation/scripts/mission-digest.ts\`. Review, annotate, then archive or promote findings.

## MCC snapshot

| Field | Value |
|-------|-------|
| Callsign | ${mc.callsign} |
| Phase | **${mc.phase}** / telemetry **${telemetry.mission_phase}** |
| Systems | ${telemetry.overall_status} |
| Wet mass target | ${mass.wet_mass_kg} kg @ ~${mass.target_float_altitude_km} km float |
| Funding goal | $${mc.funding_goal_usd.toLocaleString()} |
| Site tiers | ${Object.values(funding.tiers).map((t) => `${t.name} (cap ${t.capacity})`).join('; ')} |

### Systems board

${telemetry.systems.map((s) => `- **${s.label}**: ${s.status}`).join('\n')}

## P0 open work (${p0.length})

${p0.length ? p0.map((t) => `- [ ] **${t.id}** — ${t.title} _(${t.area})_`).join('\n') : '_None — re-prioritize tasks.json_'}

## All open tasks (${openTasks.length})

${openTasks
  .slice(0, 20)
  .map((t) => `- [${t.priority}] ${t.title} — \`${t.status}\``)
  .join('\n')}

## Risk radar (open / mitigating)

${criticalRisks.map((r) => `- **${r.id}** [${r.impact}/${r.likelihood}] ${r.title} — _${r.status}_`).join('\n')}

_Full register: \`site/content/data/risks.json\` (${openRisks.length} active)._

## Partner next steps

${partnerActions
  .filter((p) => p.priority === 'P0' || p.priority === 'P1')
  .map((p) => `- **${p.name}** (${p.status}): ${p.next_step}`)
  .join('\n')}

## Mission control checklist (open)

${checksOpen.map((c) => `- [ ] ${c.item}${c.due ? ` — due ${c.due}` : ''} (\`${c.status}\`)`).join('\n')}

## Timeline milestones

${timeline.map((t) => `- **${t.year}** (${t.status}): ${t.event}`).join('\n')}

## Recent research notes

${researchNotes.map((f) => `- \`research/notes/${f}\``).join('\n') || '_No notes yet_'}

## Agent / human actions this week

1. [ ] Fill or close one research brief under \`research/notes/\`
2. [ ] Advance one P0 task or update its status in \`tasks.json\`
3. [ ] Touch one risk mitigation (status or notes)
4. [ ] One partner next_step completed + pipeline updated
5. [ ] Social draft posted or scheduled (from \`automation/social-drafts/\`)
6. [ ] Run \`npx tsx automation/scripts/evolve.ts full\` if content changed

## Command palette

\`\`\`bash
npx tsx automation/scripts/evolve.ts digest
npx tsx automation/scripts/evolve.ts health
npx tsx automation/scripts/evolve.ts links
npx tsx automation/scripts/evolve.ts kb
npx tsx automation/scripts/evolve.ts press
\`\`\`

---
Generated ${new Date().toISOString()} · do not hand-edit structure; append notes below the line if needed.
`;

const outDir = join(root, 'research/notes');
mkdirSync(outDir, { recursive: true });
const outPath = join(outDir, `${date}-mission-digest.md`);
writeFileSync(outPath, md, 'utf8');
console.log('Wrote', outPath);

// Also refresh latest pointer
writeFileSync(join(outDir, 'LATEST-DIGEST.md'), md, 'utf8');
console.log('Wrote research/notes/LATEST-DIGEST.md');
