/**
 * Weekly research brief scaffold.
 *
 * Creates a dated research note + optional MDX draft skeleton for PR review.
 * Designed for GitHub Actions (no live LLM required). Agents can enrich offline.
 *
 * Usage:
 *   npx tsx automation/scripts/research-weekly.ts
 *   RESEARCH_DATE=2026-07-08 npx tsx automation/scripts/research-weekly.ts
 */
import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(__dirname, '../..');
const date = process.env.RESEARCH_DATE || new Date().toISOString().slice(0, 10);
const branchHint = `research/${date}`;

const researchDir = join(root, 'research/notes');
const updatesDir = join(root, 'site/content/updates');
const briefPath = join(researchDir, `${date}-research-brief.md`);
const mdxPath = join(updatesDir, `${date}-research-draft.mdx`);

mkdirSync(researchDir, { recursive: true });
mkdirSync(updatesDir, { recursive: true });

const checklist = `
# Research brief — ${date}

> Auto-generated scaffold. Fill during human/agent research cycle, then PR.

## Search targets

- [ ] Venus cloud layer / aerobot news (last 14 days)
- [ ] Rocket Lab / private Venus mission updates
- [ ] Super-pressure balloon / fluoropolymer materials
- [ ] Sensor / mass-spec miniaturization relevant to ~1–5 kg pods
- [ ] X/Twitter signals: @NephelisCo mentions, Venus science chatter

## Suggested tool calls (Grok / agents)

1. \`web_search\` — "Venus balloon aerobot 2026"
2. \`web_search\` — "Rocket Lab Venus Life Finder"
3. \`x_semantic_search\` — Venus cloud exploration private mission
4. Update files:
   - \`research/science/\`
   - \`research/competitors/\`
   - \`site/content/data/timeline.json\` (only if milestone-level)
   - new MDX under \`site/content/updates/\` when public-facing

## Findings (fill in)

### 1.

Sources:

### 2.

Sources:

### 3.

Sources:

## Proposed site changes

- [ ] No public site change needed
- [ ] New MDX update
- [ ] timeline.json tweak
- [ ] heritage.json entry
- [ ] specs.json numbers

## Social draft bullets (for social-draft.ts)

1.
2.
3.

---
Generated by automation/scripts/research-weekly.ts · branch hint: \`${branchHint}\`
`.trimStart();

if (!existsSync(briefPath)) {
  writeFileSync(briefPath, checklist, 'utf8');
  console.log('Wrote', briefPath);
} else {
  console.log('Exists, skipped', briefPath);
}

const mdx = `export const meta = {
  title: "Research draft — ${date}",
  date: "${date}",
  draft: true,
};

# Research draft — ${date}

_This is an auto-scaffolded draft. Do not publish until reviewed._

## Highlights

- TBD after research cycle

## Sources

- TBD

## Implications for Project AETHER

- TBD
`;

if (!existsSync(mdxPath)) {
  writeFileSync(mdxPath, mdx, 'utf8');
  console.log('Wrote', mdxPath);
} else {
  console.log('Exists, skipped', mdxPath);
}

// Summary for GH Action step summary
const summaryPath = process.env.GITHUB_STEP_SUMMARY;
if (summaryPath) {
  const existing = existsSync(summaryPath) ? readFileSync(summaryPath, 'utf8') : '';
  writeFileSync(
    summaryPath,
    existing +
      `\n## Research weekly\n- Brief: \`research/notes/${date}-research-brief.md\`\n- Draft MDX: \`site/content/updates/${date}-research-draft.mdx\`\n- Open a PR from branch \`${branchHint}\` after filling findings.\n`,
    'utf8'
  );
}

console.log('\nNext: fill findings, refine MDX, open PR for review (do not auto-merge).');
