/**
 * Email LATEST-DIGEST.md to TEAM_EMAIL via Resend (optional, human-gated).
 *
 * Requires: RESEND_API_KEY, optional RESEND_FROM_EMAIL, TEAM_EMAIL
 * Usage:
 *   RESEND_API_KEY=re_... npx tsx automation/scripts/send-digest-email.ts
 *   DRY_RUN=1 npx tsx automation/scripts/send-digest-email.ts
 */
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const root = join(__dirname, '../..');
const digestPath = join(root, 'research/notes/LATEST-DIGEST.md');
const dry = process.env.DRY_RUN === '1' || process.env.DRY_RUN === 'true';

if (!existsSync(digestPath)) {
  console.error('No LATEST-DIGEST.md — run evolve.ts digest first');
  process.exit(1);
}

const body = readFileSync(digestPath, 'utf8');
const team = process.env.TEAM_EMAIL || 'ehren@nephelisindustries.com';
const from =
  process.env.RESEND_FROM_EMAIL || 'Nephelis MCC <onboarding@resend.dev>';
const key = process.env.RESEND_API_KEY;
const date = new Date().toISOString().slice(0, 10);
const subject = `Nephelis mission digest — ${date}`;

// Simple markdown → HTML-ish
const html = `<pre style="font-family:ui-monospace,monospace;font-size:13px;white-space:pre-wrap;line-height:1.45">${body
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')}</pre>
<p style="color:#888;font-size:12px">Generated by automation/scripts/send-digest-email.ts · human-gated</p>`;

if (dry || !key) {
  console.log(dry ? 'DRY_RUN — would send:' : 'No RESEND_API_KEY — would send:');
  console.log(`  from: ${from}`);
  console.log(`  to:   ${team}`);
  console.log(`  subj: ${subject}`);
  console.log(`  body: ${body.length} chars`);
  if (!key && !dry) process.exit(0);
  process.exit(0);
}

async function main() {
  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${key}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from,
      to: [team],
      subject,
      html,
      text: body,
    }),
  });
  const json = await res.json();
  if (!res.ok) {
    console.error('Resend error', json);
    process.exit(1);
  }
  console.log('Sent digest email', json);
}

main();
